# Generated by Django 3.1.3 on 2020-12-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'verbose_name': 'Ticket Attachment', 'verbose_name_plural': 'Ticket Attachments'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'verbose_name': 'Ticket Comment', 'verbose_name_plural': 'Ticket Comments'},
        ),
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'verbose_name': 'Ticket History', 'verbose_name_plural': 'Ticket Histories'},
        ),
        migrations.AlterModelOptions(
            name='ticketnotification',
            options={'verbose_name': 'Ticket Notification', 'verbose_name_plural': 'Ticket Notifications'},
        ),
        migrations.AlterModelOptions(
            name='ticketpriority',
            options={'verbose_name': 'Ticket Priority', 'verbose_name_plural': 'Ticket Priorities'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'verbose_name': 'Ticket Status', 'verbose_name_plural': 'Ticket Statuses'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name': 'Ticket Type', 'verbose_name_plural': 'Ticket Types'},
        ),
    ]
