# Generated by Django 3.1.3 on 2020-12-10 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20201208_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='auth.user'),
            preserve_default=False,
        ),
    ]
