# Generated by Django 3.1.3 on 2020-12-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201211_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='project_id',
            new_name='project',
        ),
    ]
