# Generated by Django 3.1.3 on 2020-12-20 07:03
from django.db import migrations


def add_ticket_priorities(apps, schema_editor):
    TicketPriority = apps.get_model('home', 'TicketPriority')
    priority = TicketPriority(name='Low', description='Low')
    priority.save()
    priority = TicketPriority(name='Medium', description='Medium')
    priority.save()
    priority = TicketPriority(name='High', description='High')
    priority.save()
    priority = TicketPriority(name='Critical', description='Critical')
    priority.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201220_0652'),
    ]

    operations = [
        migrations.RunPython(add_ticket_priorities)
    ]
