# Generated by Django 3.1.3 on 2020-12-20 07:52

from django.db import migrations


class Migration(migrations.Migration):
    def add_ticket_statuses(apps, schema_editor):
        TicketStatus = apps.get_model('home', 'TicketStatus')
        status = TicketStatus(
            name='New', description='Ticket automatically assigned this status on creation')
        status.save()
        status = TicketStatus(
            name='Waiting for support',
            description='Ticket automatically changed to this status when it is assigned to a developer'
        )
        status.save()
        status = TicketStatus(
            name='Waiting for customer',
            description='Ticket is waiting on a response from a third-party source'
        )
        status.save()
        status = TicketStatus(
            name='On hold',
            description='Work on the ticket has been suspended'
        )
        status.save()
        status = TicketStatus(
            name='Resolved',
            description='The issue raised in the ticket has been resolved'
        )
        status.save()

    dependencies = [
        ('home', '0007_auto_20201220_0703'),
    ]

    operations = [
        migrations.RunPython(add_ticket_statuses)
    ]
