# Generated by Django 3.1.3 on 2020-12-24 10:03

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201222_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketattachment',
            name='attachment_url',
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='attachment',
            field=models.FileField(null=True, upload_to=home.models.user_directory_path),
        ),
    ]
