# Generated by Django 3.1.3 on 2020-12-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201224_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketattachment',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='ticketattachment',
            old_name='user_id',
            new_name='user',
        ),
    ]
