# Generated by Django 3.1.3 on 2020-12-24 10:44

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201224_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(null=True, upload_to=home.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='TicketAttachment',
        ),
    ]
