# Generated by Django 3.1.3 on 2020-12-24 14:13

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201224_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(upload_to=home.models.user_directory_path),
        ),
    ]
