# Generated by Django 3.1.3 on 2020-12-24 16:21

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_ticket_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(null=True, upload_to=home.models.user_directory_path),
        ),
    ]
