# Generated by Django 3.1.3 on 2020-12-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201224_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
