# Generated by Django 3.1.3 on 2020-12-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20201224_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketnotification',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='ticketnotification',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='ticketnotification',
            name='ticket_id',
        ),
        migrations.DeleteModel(
            name='TicketHistory',
        ),
        migrations.DeleteModel(
            name='TicketNotification',
        ),
    ]
